import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/components/Login.module.scss";
import { InputText } from "primereact/inputtext";
import { Button } from "primereact/button";

const inter = Inter({ subsets: ["latin"] });

export default function Login(
  {setName, setPassword, handleLogin}: 
  {setName: any, setPassword: any, handleLogin: any}
) {

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.formContainer}>
          <InputText placeholder="Pseudo" onChange={(e) => setName(e.target.value)}/>
          <InputText placeholder="Password" type="password" onChange={(e) => setPassword(e.target.value)}/>
          <Button label="Login" onClick={handleLogin}/>
        </div>
      </main>
    </>
  );
}
