import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/pages/Admin.module.scss";
import { InputText } from "primereact/inputtext";
import { Button } from "primereact/button";
import { useState } from "react";
import { login } from "@/services/Auth/functions/login";

const inter = Inter({ subsets: ["latin"] });

export default function Admin() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleLogin = async () => {
    const result = await login(email, password);
    console.log(result);
  };

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.formContainer}>
          <InputText placeholder="Email" onChange={(e) => setEmail(e.target.value)}/>
          <InputText placeholder="Password" type="password" onChange={(e) => setPassword(e.target.value)}/>
          <Button label="Login" onClick={handleLogin}/>
        </div>
      </main>
    </>
  );
}
